require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PartsController do

  def mock_part(stubs={})
    @mock_part ||= mock_model(Part, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all parts as @parts" do
      Part.stub(:all) { [mock_part] }
      get :index
      assigns(:parts).should eq([mock_part])
    end
  end

  describe "GET show" do
    it "assigns the requested part as @part" do
      Part.stub(:find).with("37") { mock_part }
      get :show, :id => "37"
      assigns(:part).should be(mock_part)
    end
  end

  describe "GET new" do
    it "assigns a new part as @part" do
      Part.stub(:new) { mock_part }
      get :new
      assigns(:part).should be(mock_part)
    end
  end

  describe "GET edit" do
    it "assigns the requested part as @part" do
      Part.stub(:find).with("37") { mock_part }
      get :edit, :id => "37"
      assigns(:part).should be(mock_part)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created part as @part" do
        Part.stub(:new).with({'these' => 'params'}) { mock_part(:save => true) }
        post :create, :part => {'these' => 'params'}
        assigns(:part).should be(mock_part)
      end

      it "redirects to the created part" do
        Part.stub(:new) { mock_part(:save => true) }
        post :create, :part => {}
        response.should redirect_to(part_url(mock_part))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved part as @part" do
        Part.stub(:new).with({'these' => 'params'}) { mock_part(:save => false) }
        post :create, :part => {'these' => 'params'}
        assigns(:part).should be(mock_part)
      end

      it "re-renders the 'new' template" do
        Part.stub(:new) { mock_part(:save => false) }
        post :create, :part => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested part" do
        Part.stub(:find).with("37") { mock_part }
        mock_part.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :part => {'these' => 'params'}
      end

      it "assigns the requested part as @part" do
        Part.stub(:find) { mock_part(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:part).should be(mock_part)
      end

      it "redirects to the part" do
        Part.stub(:find) { mock_part(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(part_url(mock_part))
      end
    end

    describe "with invalid params" do
      it "assigns the part as @part" do
        Part.stub(:find) { mock_part(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:part).should be(mock_part)
      end

      it "re-renders the 'edit' template" do
        Part.stub(:find) { mock_part(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested part" do
      Part.stub(:find).with("37") { mock_part }
      mock_part.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the parts list" do
      Part.stub(:find) { mock_part }
      delete :destroy, :id => "1"
      response.should redirect_to(parts_url)
    end
  end

end
