require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SourcesController do

  def mock_source(stubs={})
    @mock_source ||= mock_model(Source, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all sources as @sources" do
      Source.stub(:all) { [mock_source] }
      get :index
      assigns(:sources).should eq([mock_source])
    end
  end

  describe "GET show" do
    it "assigns the requested source as @source" do
      Source.stub(:find).with("37") { mock_source }
      get :show, :id => "37"
      assigns(:source).should be(mock_source)
    end
  end

  describe "GET new" do
    it "assigns a new source as @source" do
      Source.stub(:new) { mock_source }
      get :new
      assigns(:source).should be(mock_source)
    end
  end

  describe "GET edit" do
    it "assigns the requested source as @source" do
      Source.stub(:find).with("37") { mock_source }
      get :edit, :id => "37"
      assigns(:source).should be(mock_source)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created source as @source" do
        Source.stub(:new).with({'these' => 'params'}) { mock_source(:save => true) }
        post :create, :source => {'these' => 'params'}
        assigns(:source).should be(mock_source)
      end

      it "redirects to the created source" do
        Source.stub(:new) { mock_source(:save => true) }
        post :create, :source => {}
        response.should redirect_to(source_url(mock_source))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved source as @source" do
        Source.stub(:new).with({'these' => 'params'}) { mock_source(:save => false) }
        post :create, :source => {'these' => 'params'}
        assigns(:source).should be(mock_source)
      end

      it "re-renders the 'new' template" do
        Source.stub(:new) { mock_source(:save => false) }
        post :create, :source => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested source" do
        Source.stub(:find).with("37") { mock_source }
        mock_source.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :source => {'these' => 'params'}
      end

      it "assigns the requested source as @source" do
        Source.stub(:find) { mock_source(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:source).should be(mock_source)
      end

      it "redirects to the source" do
        Source.stub(:find) { mock_source(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(source_url(mock_source))
      end
    end

    describe "with invalid params" do
      it "assigns the source as @source" do
        Source.stub(:find) { mock_source(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:source).should be(mock_source)
      end

      it "re-renders the 'edit' template" do
        Source.stub(:find) { mock_source(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested source" do
      Source.stub(:find).with("37") { mock_source }
      mock_source.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the sources list" do
      Source.stub(:find) { mock_source }
      delete :destroy, :id => "1"
      response.should redirect_to(sources_url)
    end
  end

end
